name: html_to_pdf
description: Flutter plugin for generating PDF documents from HTML code templates
version: 0.7.2
homepage: https://github.com/penkzhou/html_to_pdf

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.oldautumn.flutter.html_to_pdf
        pluginClass: HtmlToPdfPlugin
      ios:
        pluginClass: HtmlToPdfPlugin


