name: Verify that the packages are releasable.
on:
  push:
    branches: [master]
  pull_request:

jobs:
 publish-packages:
   name: Verify packages
   runs-on: [ ubuntu-latest ]
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.16.8'
     - run: flutter pub publish --dry-run
